const KEY="neuro-binder-v1";
const empty=()=>({profile:{name:"",dob:"",pronouns:"",diagnosis:"",bloodType:"",photo:"",notes:""},contacts:[],medical:{allergies:"",meds:"",conditions:"",providers:"",insurance:"",notes:""},talk:{style:"",phrases:"",doSay:"",dontSay:"",devices:"",notes:""},sensory:{likes:"",avoids:"",calming:"",overload:"",notes:""},crisis:{triggers:"",signs:"",howToHelp:"",after:"",notes:""},safety:{wander:"",ifMissing:"",safePlaces:"",tracking:"",notes:""},daily:{morning:"",day:"",evening:"",food:"",sleep:"",notes:""},papers:[]});
let data=load();
function load(){try{const raw=localStorage.getItem(KEY);return raw?{...empty(),...JSON.parse(raw)}:empty()}catch{return empty()}}
function save(){localStorage.setItem(KEY,JSON.stringify(data));renderTiles()}
function toast(msg){const el=document.getElementById("toast");el.textContent=msg;el.classList.add("on");setTimeout(()=>el.classList.remove("on"),1800)}
const SECTIONS=[
{id:"profile",title:"Profile",hint:"Who this binder is for.",color:"#22d3ee",filled:d=>!!(d.profile.name||d.profile.diagnosis)},
{id:"contacts",title:"Contacts",hint:"People to call.",color:"#c084fc",filled:d=>d.contacts.length>0},
{id:"medical",title:"Medical",hint:"Allergies, meds, care team.",color:"#f472b6",filled:d=>!!(d.medical.allergies||d.medical.meds)},
{id:"talk",title:"Talk",hint:"How to communicate.",color:"#38bdf8",filled:d=>!!(d.talk.style||d.talk.phrases)},
{id:"sensory",title:"Sensory",hint:"What helps and what hurts.",color:"#facc15",filled:d=>!!(d.sensory.likes||d.sensory.avoids)},
{id:"crisis",title:"Crisis",hint:"Plan when things spike.",color:"#fb7185",filled:d=>!!(d.crisis.howToHelp||d.crisis.triggers)},
{id:"safety",title:"Safety",hint:"Wander risk and if missing.",color:"#34d399",filled:d=>!!(d.safety.ifMissing||d.safety.wander)},
{id:"daily",title:"Daily",hint:"Routine that keeps the day steady.",color:"#a78bfa",filled:d=>!!(d.daily.morning||d.daily.day)},
{id:"papers",title:"Papers",hint:"IEP, insurance, IDs — notes only.",color:"#fb7185",filled:d=>d.papers.length>0}
];
const pieceSvg=color=>`<svg class="piece" viewBox="0 0 100 100"><use href="#piece" fill="${color}"/></svg>`;
function renderTiles(){document.getElementById("tiles").innerHTML=SECTIONS.map(s=>`<button class="tile ${s.filled(data)?"":"empty"}" data-open="${s.id}">${pieceSvg(s.color)}<h3>${s.title}</h3><span>${s.filled(data)?"Has notes":"Empty"}</span></button>`).join("")}
function show(id){document.querySelectorAll(".screen").forEach(el=>el.classList.toggle("on",el.id===id))}
function field(name,label,value,extra=""){const tag=extra.includes("rows")?"textarea":"input";const type=extra.includes("type=")?"":'type="text"';return `<label>${label}<${tag} ${type} ${extra} data-f="${name}">${tag==="textarea"?esc(value):""}</${tag}></label>`.replace(`data-f="${name}">`,tag==="input"?`data-f="${name}" value="${escAttr(value)}">`:`data-f="${name}">`)}
function esc(s){return String(s||"").replace(/[&<>]/g,c=>({"&":"&","<":"<",">":">"}[c]))}
function escAttr(s){return esc(s).replace(/"/g,""")}
function bindFields(obj){document.querySelectorAll("[data-f]").forEach(el=>{el.addEventListener("input",()=>{obj[el.dataset.f]=el.value;save()})})}
function openSection(id){const meta=SECTIONS.find(s=>s.id===id);document.getElementById("editTitle").textContent=meta.title;document.getElementById("editHint").textContent=meta.hint;({profile:renderProfile,contacts:renderContacts,medical:()=>renderForm(data.medical,[["allergies","Allergies","rows=3"],["meds","Medications","rows=3"],["conditions","Conditions","rows=2"],["providers","Doctors / therapists","rows=2"],["insurance","Insurance / member IDs"],["notes","Notes","rows=3"]]),talk:()=>renderForm(data.talk,[["style","How they communicate","rows=2"],["phrases","Useful phrases","rows=3"],["doSay","Do say","rows=2"],["dontSay","Don't say","rows=2"],["devices","AAC / devices"],["notes","Notes","rows=2"]]),sensory:()=>renderForm(data.sensory,[["likes","Seeks / likes","rows=3"],["avoids","Avoids","rows=3"],["calming","What calms","rows=3"],["overload","Signs of overload","rows=2"],["notes","Notes","rows=2"]]),crisis:()=>renderForm(data.crisis,[["triggers","Triggers","rows=2"],["signs","Early signs","rows=2"],["howToHelp","How to help","rows=4"],["after","Aftercare","rows=2"],["notes","Notes","rows=2"]]),safety:()=>renderForm(data.safety,[["wander","Wander / elopement notes","rows=2"],["ifMissing","If missing — what to do","rows=4"],["safePlaces","Safe / likely places","rows=2"],["tracking","Tracking / ID jewelry"],["notes","Notes","rows=2"]]),daily:()=>renderForm(data.daily,[["morning","Morning","rows=3"],["day","Day / school / work","rows=3"],["evening","Evening","rows=3"],["food","Food notes","rows=2"],["sleep","Sleep","rows=2"],["notes","Notes","rows=2"]]),papers:renderPapers})[id]();show("editor")}
function renderForm(obj,fields){document.getElementById("editBody").innerHTML=`<div class="card">${fields.map(([n,l,extra])=>field(n,l,obj[n],extra||"")).join("")}</div>`;bindFields(obj)}
function renderProfile(){const p=data.profile;document.getElementById("editBody").innerHTML=`<div class="card"><div class="photo-row"><img class="avatar" id="avatar" alt="" src="${p.photo||"icon.svg"}"/><div><button class="btn btn-ghost" id="photoBtn">Add photo</button><input id="photoIn" type="file" accept="image/*" hidden/></div></div>${field("name","Name",p.name)}<div class="row">${field("dob","Birthday",p.dob,'type="date"')}${field("pronouns","Pronouns",p.pronouns)}</div>${field("diagnosis","Diagnosis / notes",p.diagnosis,"rows=2")}${field("bloodType","Blood type",p.bloodType)}${field("notes","Other",p.notes,"rows=3")}</div>`;bindFields(p);const pin=document.getElementById("photoIn");document.getElementById("photoBtn").onclick=()=>pin.click();pin.onchange=()=>{const file=pin.files[0];if(!file)return;if(file.size>700000)return toast("Photo too large. Use a smaller one.");const reader=new FileReader();reader.onload=()=>{p.photo=reader.result;document.getElementById("avatar").src=p.photo;save()};reader.readAsDataURL(file)}}
function renderContacts(){document.getElementById("editBody").innerHTML=`<button class="btn btn-qr" id="addContact">Add contact</button><div class="list" id="contactList"></div>`;document.getElementById("addContact").onclick=()=>{data.contacts.push({name:"",relation:"",phone:"",email:"",emergency:true,notes:""});save();paintContacts()};paintContacts()}
function paintContacts(){const list=document.getElementById("contactList");if(!data.contacts.length){list.innerHTML=`<p class="hint">No contacts yet.</p>`;return}list.innerHTML=data.contacts.map((c,i)=>`<div class="card"><label>Name<input data-ci="${i}" data-k="name" value="${escAttr(c.name)}"></label><div class="row"><label>Relation<input data-ci="${i}" data-k="relation" value="${escAttr(c.relation)}"></label><label>Phone<input data-ci="${i}" data-k="phone" value="${escAttr(c.phone)}" type="tel"></label></div><label>Email<input data-ci="${i}" data-k="email" value="${escAttr(c.email)}" type="email"></label><label>Notes<textarea data-ci="${i}" data-k="notes" rows="2">${esc(c.notes)}</textarea></label><label><input data-ci="${i}" data-k="emergency" type="checkbox" ${c.emergency?"checked":""}> Emergency contact</label><button class="btn btn-danger" data-del="${i}">Remove</button></div>`).join("");list.querySelectorAll("[data-ci]").forEach(el=>{const apply=()=>{const item=data.contacts[+el.dataset.ci];item[el.dataset.k]=el.type==="checkbox"?el.checked:el.value;save()};el.addEventListener("input",apply);el.addEventListener("change",apply)});list.querySelectorAll("[data-del]").forEach(btn=>{btn.onclick=()=>{data.contacts.splice(+btn.dataset.del,1);save();paintContacts()}})}
function renderPapers(){document.getElementById("editBody").innerHTML=`<p class="hint">Store titles and where the paper lives. Big files stay off the phone.</p><button class="btn btn-qr" id="addPaper">Add paper</button><div class="list" id="paperList"></div>`;document.getElementById("addPaper").onclick=()=>{data.papers.push({title:"",kind:"",where:"",notes:""});save();paintPapers()};paintPapers()}
function paintPapers(){const list=document.getElementById("paperList");if(!data.papers.length){list.innerHTML=`<p class="hint">No papers yet.</p>`;return}list.innerHTML=data.papers.map((p,i)=>`<div class="card"><label>Title<input data-pi="${i}" data-k="title" value="${escAttr(p.title)}"></label><div class="row"><label>Kind<input data-pi="${i}" data-k="kind" value="${escAttr(p.kind)}" placeholder="IEP, insurance..."></label><label>Where it is<input data-pi="${i}" data-k="where" value="${escAttr(p.where)}"></label></div><label>Notes<textarea data-pi="${i}" data-k="notes" rows="2">${esc(p.notes)}</textarea></label><button class="btn btn-danger" data-pdel="${i}">Remove</button></div>`).join("");list.querySelectorAll("[data-pi]").forEach(el=>{el.addEventListener("input",()=>{data.papers[+el.dataset.pi][el.dataset.k]=el.value;save()})});list.querySelectorAll("[data-pdel]").forEach(btn=>{btn.onclick=()=>{data.papers.splice(+btn.dataset.pdel,1);save();paintPapers()}})}
function cardText(){const phones=data.contacts.filter(c=>c.phone).map(c=>`${c.name||"Contact"}${c.relation?" ("+c.relation+")":""}: ${c.phone}`).join(" | ");return ["NEURO-BINDER CARD",data.profile.name?`Name: ${data.profile.name}`:"Name: —",data.profile.diagnosis?`Notes: ${data.profile.diagnosis}`:null,`Allergies: ${data.medical.allergies||"—"}`,`Meds: ${data.medical.meds||"—"}`,`Phones: ${phones||"—"}`,`How to help: ${data.crisis.howToHelp||"—"}`,`If missing: ${data.safety.ifMissing||"—"}`].filter(Boolean).join("\n")}
function makeQr(){const text=cardText();const box=document.getElementById("qrBox");box.innerHTML="";document.getElementById("qrText").textContent=text;new QRCode(box,{text,width:220,height:220,colorDark:"#140824",colorLight:"#ffffff",correctLevel:QRCode.CorrectLevel.M});document.getElementById("qrModal").classList.add("on")}
document.getElementById("tiles").addEventListener("click",e=>{const btn=e.target.closest("[data-open]");if(btn)openSection(btn.dataset.open)});
document.getElementById("backHome").onclick=()=>{renderTiles();show("home")};
document.getElementById("makeQr").onclick=makeQr;
document.getElementById("closeQr").onclick=()=>document.getElementById("qrModal").classList.remove("on");
document.getElementById("qrModal").addEventListener("click",e=>{if(e.target.id==="qrModal")e.target.classList.remove("on")});
document.getElementById("copyCard").onclick=async()=>{try{await navigator.clipboard.writeText(cardText());toast("Card copied")}catch{toast("Copy failed")}};
document.getElementById("exportBtn").onclick=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));a.download="neuro-binder-backup.json";a.click();URL.revokeObjectURL(a.href);toast("Backup saved")};
document.getElementById("importBtn").onclick=()=>document.getElementById("fileIn").click();
document.getElementById("fileIn").onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{data={...empty(),...JSON.parse(reader.result)};save();toast("Restored")}catch{toast("Bad backup file")}};reader.readAsText(file);e.target.value=""};
renderTiles();
